### ISSUE TITLE
Add support for brazilian portuguese (PT-BR)

### ISSUE THREAD

**Issue by paladini** [carsonip/alexa-pomodoro#14]
Add support for this device work with Brazilian Portuguese language (PT-BR). It's current being tested and released as a Beta Test by Amazon. Only a few people has it enabled at the time, but Amazon will officially release this language very soon.

May I submit a pull request with the code that needed to be implemented in order to support this language?

Thanks for the project!

**Comment by paladini** [comment]
It's a little bit related to #9 , #10 and #11 .

**Comment by carsonip** [comment]
Hello @paladini, sorry for the late reply. I would add support for a new language if there is someone who volunteers to do the translation work. Please feel free to submit a PR!
