### ISSUE TITLE
Does not show progress on Echo Show 5

### ISSUE THREAD

**Issue by craigdougken** [carsonip/alexa-pomodoro#18]
Is there any way to show the timer countdown on Echo Show?
It currently just shows "Now Playing"

**Comment by carsonip** [comment]
I doubt it. The current implementation is that the skill plays an audio of 25mins, 20mins, 5mins. It was the only way to bypass some restrictions in the past. There may be new ways to implement a pomodoro skill but it will require a rewrite.
