### ISSUE TITLE
Paused a timer... can't get it to start again.

### ISSUE THREAD

**Issue by tanafranko** [carsonip/alexa-pomodoro#2]
I started a timer and then had to pause it. When I try to restart by saying "continue" or "start" or "unpause" I hear "Operation not supported."

**Comment by carsonip** [comment]
Hi, thanks for reporting an issue. I'll look into this and get back to you soon.

**Comment by carsonip** [comment]
Hi @tanafranko, I have identified the problem and fixed it in cca2ec83c60411fcc32b53bd6c6e444db684a9bf. Will deploy it soon.

**Comment by carsonip** [comment]
The fix is now live.
