### ISSUE TITLE
Can I start a timer and skip the instructions?  

### ISSUE THREAD

**Issue by jcskw** [carsonip/alexa-pomodoro#4]
I open Tomato Helper in alexa and have to listed to the "if you are using tomato helper for the first time..."  every time I want to use Tomato Helper.  Is there a command I can issue when opening Tomato Helper to go right into the timer?  

I'm forced to use Tomato Helper sporadically thru the day based on my meetings.

Thanks for an AWESOME service
Jim

**Comment by carsonip** [comment]
Thanks for supporting the skill. Have you tried something like "Ask tomato helper to start (silent) timer" or "Ask tomato helper for (silent) timer"? I just tried and it should work.

**Comment by jcskw** [comment]
that did it!  thanks so much!

**Comment by carsonip** [comment]
Good to know. Also, I suppose I have to improve the instructions.

**Comment by jcskw** [comment]
Is there any way to ask tomato helper to have a longer timer like 35 minutes?  ;)

**Comment by carsonip** [comment]
It doesn't have that one since Pomodoro is 25 minutes long.
