### ISSUE TITLE
this command "Alexa, ask tomato helper for progress"  isn't working 

### ISSUE THREAD

**Issue by arveyMon** [carsonip/alexa-pomodoro#6]
its restarting the timer

**Comment by carsonip** [comment]
Sorry for replying late. I'll take a look into it soon.

**Comment by carsonip** [comment]
It works for me when the timer is activated. What region are you in?

**Comment by arveyMon** [comment]
India, it didn't for you , it restarted the timer

**Comment by carsonip** [comment]
Thank you for the info. I'll look into it soon.

**Comment by carsonip** [comment]
@arveyMon I have identified the issue. The fix is coming out soon. I'll let you know when it is fixed. Thanks!

**Comment by carsonip** [comment]
@arveyMon The update is now live. Please check whether it is working.
