### ISSUE TITLE
Silent timer default

### ISSUE THREAD

**Issue by paulomcnally** [carsonip/alexa-pomodoro#7]
It's a bit disturbing to hear the clock sound, have you thought that silent mode is enabled by default?

Thanks for reading me.

**Comment by carsonip** [comment]
Thanks for the comment. I have also received comments about people finding the tick tock useful. In terms of user experience, I suppose when there is no sound, people may think the skill is broken. I will keep the tick tock sound as default until there are more people who ask for a change of default. For those who want the change please +1 in this issue. I'll close this issue for now.
