### ISSUE TITLE
Spanish support

### ISSUE THREAD

**Issue by paulomcnally** [carsonip/alexa-pomodoro#9]
Have you thought about publishing for the Spanish language?

**Comment by carsonip** [comment]
If anyone is willing to take up the translation work, why not? I can take out all the English words used to ease the translation process.

**Comment by carsonip** [comment]
Hi @paulomcnally, thanks for your work! I have submitted to Amazon for review. Hopefully it will be published in a few days.

**Comment by carsonip** [comment]
@paulomcnally Please note the certification feedback for Spanish support of the skill:

> 
> Issues with skill in Spanish (Mexico):
> 
> ___________________________________________________________________________________
> 
> Issues observed on devices without display (Echo, Echo Dot)
> 
> 1. The example phrases that you chose to present to users in the Alexa app currently use unsupported launch phrasing or an incorrect invocation name.
> 
>  
> 
> Third example phrase:
> 
> Actual: " Alexa, siguiente."
> 
> Expected: "Siguiente"
> 
>  
> 
> Please see our documentation on understanding how users invoke custom skills for more information on supported launch phrasing.
> 
>  
> 
> 2. The welcome prompt provided must be appropriate to the context of the skill’s functionality as defined in its description. Also, it should help the users to navigate to use the skill’s functionality.
> 
>  
> 
> Steps To Reproduce:
> 
> User: "Alexa, lanza ayudante de tomate."
> 
> Skill: "Bienvenido al ayudante de tomate. Si esta es la primera vez que usas esta habilidad, diga, ayuda. Recuerde, cuando suene la alarma, diga, continuar, para detenerla. Ahora, diga, iniciar temporizador, o iniciar temporizador silencioso."
> 
>  
> 
> Please replace the word "habilidad" with "skill" in all the skill metadata, including the description and help prompt.
> 
>  
> 
> Please see our Best Practices for the Welcome Experience and Prompting in Alexa Skills for more guidance.
> 
>  
> 
> 3. The description displayed in the skill's detail card must be relevant and contain detailed information about the skill's functionality. Please provide these details by mentioning what kind of devices the skill supports, and their functionalities. This will help the users to understand the skill’s usage.
> 
>  
> 
> Actual: "Esta es una habilidad no oficial de la Técnica Pomodoro"
> 
> Expected: "Esta es una skill no oficial de la Técnica Pomodoro"
> 
>  
> 
> Actual: "Esta habilidad no está asociada de ninguna manera con el "Técnica Pomodoro", "Pomodoro" y Francesco Cirillo."
> 
> Expected: "Esta skill no está asociada de ninguna manera con el "Técnica Pomodoro", "Pomodoro" y Francesco Cirillo."
> 
>  
> 
> Please replace the word "habilidad" with "skill".
> 
>  
> 
> Please see our Submission Checklist for guidance on skill descriptions.
> 
> ___________________________________________________________________________________
> 
> Issues with skill in Spanish (Spain):
> 
> ___________________________________________________________________________________
> 
> Issues observed on devices without display (Echo, Echo Dot)
> 
>  
> 
> 1. The example phrases that you choose to present to users in the companion app must be selected from your sample utterances. For example: "Alexa, ask {your invocation name} to {sample utterance present in your intent}."
> 
>  
> 
> Second example phrase:
> 
> Actual: "Inicia temporizador"
> 
> Expected: "iniciar temporizador"
> 
>  
> 
> Please see our documentation for more information on ensuring your sample utterances support invocation phrases. Please also see our blogpost for more guidance on creating example phrases.
> 
>  
> 
> 2. The description displayed in the skill's detail card must be relevant and contain detailed information about the skill's functionality. Please provide these details by mentioning what kind of devices the skill supports, and their functionalities. This will help the users to understand the skill’s usage.
> 
>  
> 
> Please replace the word "habilidad" with "skill" as follows:
> 
>  
> 
> Actual: "Esta es una habilidad no oficial de la Técnica Pomodoro"
> 
> Expected: "Esta es una skill no oficial de la Técnica Pomodoro"
> 
>  
> 
> Actual: "Esta habilidad no está asociada de ninguna manera con el "Técnica Pomodoro", "Pomodoro" y Francesco Cirillo."
> 
> Expected: "Esta skill no está asociada de ninguna manera con el "Técnica Pomodoro", "Pomodoro" y Francesco Cirillo."
> 
>  
> 
> Please see our Submission Checklist for guidance on skill descriptions.
> 
>  
> 
> 3. The welcome prompt provided must be appropriate to the context of the skill’s functionality as defined in its description. Also, it should help the users to navigate to use the skill’s functionality.
> 
>  
> 
> Steps To Reproduce:
> 
> User: "Alexa, inicia ayudante de tomate"
> 
> Skill: "Bienvenido al ayudante de tomate. Si esta es la primera vez que usas esta habilidad, diga, ayuda. Recuerde, cuando suene la alarma, diga, continuar, para detenerla. Ahora, diga, iniciar temporizador, o iniciar temporizador silencioso."
> 
>  
> 
> Please replace the word "habilidad" with "skill".
> 
>  
> 
> Please see our Best Practices for the Welcome Experience and Prompting in Alexa Skills for more guidance.
> 
>  
> 
> 4. The skill does not return a help prompt that instructs users on how to navigate further into the skill’s core functionality.
> 
>  
> 
> Steps to Reproduce:
> 
> User: "Alexa, inicia ayudante de tomate"
> 
> Skill: "Bienvenido al ayudante de tomate. Si esta es la primera vez que usas esta habilidad, diga, ayuda. Recuerde, cuando suene la alarma, diga, continuar, para detenerla. Ahora, diga, iniciar temporizador, o iniciar temporizador silencioso."
> 
>  
> 
> User: "ayuda"
> 
> Skill: "Ayudante de tomate es una habilidad para rastrear pomodoro con el fin de aumentar la productividad. Cada pomodoro dura 25 minutos y cada pausa dura 5 minutos. Después de 4 pomodoros, tienes un descanso de 20 minutos. Cuando suene la alarma, digamos, a continuación. Para verificar su progreso durante el tiempo, por ejemplo, Alexa, pídale ayuda al ayudante de tomate. Para comenzar a usar el ayudante de tomate, por ejemplo, iniciar el temporizador o iniciar el temporizador en silencio."
> 
>  
> 
> Please replace the word "habilidad" with "skill".
> 
>  
> 
> Please ensure that, the help prompt ends with a question or a statement prompting users to respond, keeps the session open, and allows them to continue navigate within the skill. Please see our Submission Checklist for guidance on the help intent.
> 
>  
> 
> ___________________________________________________________________________________
> 
> Issues with skill in Spanish (U.S.):
> 
> ___________________________________________________________________________________
> 
> Issues observed on devices without display (Echo, Echo Dot)
> 
> 1. The example phrases that you chose to present to users in the Alexa app currently use unsupported launch phrasing or an incorrect invocation name.
> 
>  
> 
> Third example phrase:
> 
> Actual: "Alexa, siguiente."
> 
> Expected: "Siguiente."
> 
>  
> 
> Please see our documentation on understanding how users invoke custom skills for more information on supported launch phrasing.
> 
>  
> 
> 2. The welcome prompt provided must be appropriate to the context of the skill’s functionality as defined in its description. Also, it should help the users to navigate to use the skill’s functionality.
> 
>  
> 
> Steps To Reproduce:
> 
> User: "Alexa, inicia usted ayudante de tomate."
> 
> Skill: "Bienvenido al ayudante de tomate. Si esta es la primera vez que usas esta habilidad, diga, ayuda. Recuerde, cuando suene la alarma, diga, continuar, para detenerla. Ahora, diga, iniciar temporizador, o iniciar temporizador silencioso. "
> 
>  
> 
> Please replace the word "habilidad" with "skill" in all the skill metadata, including the description and help prompt.
> 
>  
> 
> Please see our Best Practices for the Welcome Experience and Prompting in Alexa Skills for more guidance.
> 
>  
> 
> 3. The description displayed in the skill's detail card must be relevant and contain detailed information about the skill's functionality. Please provide these details by mentioning what kind of devices the skill supports, and their functionalities. This will help the users to understand the skill’s usage.
> 
>  
> 
> Actual: "Esta es una habilidad no oficial de la Técnica Pomodoro"
> 
> Expected: "Esta es una skill no oficial de la Técnica Pomodoro"
> 
>  
> 
> Actual: "Esta habilidad no está asociada de ninguna manera con el "Técnica Pomodoro", "Pomodoro" y Francesco Cirillo."
> 
> Expected: "Esta skill no está asociada de ninguna manera con el "Técnica Pomodoro", "Pomodoro" y Francesco Cirillo."
> 
>  
> 
> Please replace the word "habilidad" with "skill".

**Comment by carsonip** [comment]
These issues have to be fixed before re-applying for certification. Please let me know if you need any help. Thanks!

**Comment by paulomcnally** [comment]
@carsonip I will work on the changes requested, today at night I will make a new PR. Thank you

**Comment by paulomcnally** [comment]
@carsonip please see https://github.com/carsonip/alexa-pomodoro/pull/12 :)

**Comment by carsonip** [comment]
Thanks! Re-submitted for certification.

**Comment by carsonip** [comment]
@paulomcnally The updated skill is now live! Please check if everything is working with the Spanish version. If so, this issue can be closed.

**Comment by paulomcnally** [comment]
I am going to try.

**Comment by paulomcnally** [comment]
It works correctly.

Thanks for taking the time.

**Comment by carsonip** [comment]
@paulomcnally Thanks for your hard work!
